create database registroFinca;
use registroFinca;

-- MySQL Script generated by MySQL Workbench
-- Tue Oct 22 09:19:34 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema registroFinca
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema registroFinca
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `registroFinca` DEFAULT CHARACTER SET utf8 ;
USE `registroFinca` ;

-- -----------------------------------------------------
-- Table `registroFinca`.`Departamento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `registroFinca`.`Departamento` (
  `idDepartamento` INT NOT NULL AUTO_INCREMENT,
  `nombreDepto` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idDepartamento`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `registroFinca`.`Municipio`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `registroFinca`.`Municipio` (
  `idMunicipio` INT NOT NULL AUTO_INCREMENT,
  `nombreMpio` VARCHAR(45) NOT NULL,
  `Departamento_idDepartamento` INT NOT NULL,
  PRIMARY KEY (`idMunicipio`, `Departamento_idDepartamento`),
  INDEX `fk_Municipio_Departamento1_idx` (`Departamento_idDepartamento` ASC),
  CONSTRAINT `fk_Municipio_Departamento1`
    FOREIGN KEY (`Departamento_idDepartamento`)
    REFERENCES `registroFinca`.`Departamento` (`idDepartamento`)
  )
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `registroFinca`.`Finca`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `registroFinca`.`Finca` (
  `idFinca` INT NOT NULL AUTO_INCREMENT,
  `nombreFinca` VARCHAR(45) NOT NULL,
  `tamanio` INT NOT NULL,
  `Municipio_idMunicipio` INT NOT NULL,
  `cantidad` VARCHAR(45) NOT NULL,
  `piscina` VARCHAR(3) NOT NULL,
  `descripcion` VARCHAR(200) NOT NULL,
  PRIMARY KEY (`idFinca`, `Municipio_idMunicipio`),
  INDEX `fk_Finca_Municipio1_idx` (`Municipio_idMunicipio` ASC),
  CONSTRAINT `fk_Finca_Municipio1`
    FOREIGN KEY (`Municipio_idMunicipio`)
    REFERENCES `registroFinca`.`Municipio` (`idMunicipio`)
  )
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `registroFinca`.`Vaca`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `registroFinca`.`Vaca` (
  `idVaca` INT NOT NULL AUTO_INCREMENT,
  `peso` INT NOT NULL,
  `edad` INT NOT NULL,
  `nombreVaca` VARCHAR(45) NOT NULL,
  `crias` VARCHAR(45) NOT NULL,
  `num_ordenada` INT NOT NULL,
  `Finca_idFinca` INT NOT NULL,
  PRIMARY KEY (`idVaca`, `Finca_idFinca`),
  INDEX `fk_Vaca_Finca1_idx` (`Finca_idFinca` ASC),
  CONSTRAINT `fk_Vaca_Finca1`
    FOREIGN KEY (`Finca_idFinca`)
    REFERENCES `registroFinca`.`Finca` (`idFinca`)
  )
ENGINE = InnoDB;

--------------------------------------------------------
-- Insert Tabla Vaca
-- -----------------------------------------------------

INSERT INTO `registrofinca`.`vaca` (`peso`, `edad`, `nombreVaca`, `crias`, `num_ordenada`, `Finca_idFinca`) VALUES ('23', '2', 'lola', 'si', '4', '1');

-- -----------------------------------------------------
-- Insert  Tabla Departamento
-- -----------------------------------------------------
INSERT INTO `registroFinca`.`Departamento` (`idDepartamento`, `nombreDepto`) VALUES ('1', 'QUINDIO');
INSERT INTO `registroFinca`.`Departamento` (`idDepartamento`, `nombreDepto`) VALUES ('2', 'RISARALDA');
INSERT INTO `registroFinca`.`Departamento` (`idDepartamento`, `nombreDepto`) VALUES ('3', 'VALLE');
INSERT INTO `registroFinca`.`Departamento` (`idDepartamento`, `nombreDepto`) VALUES ('4', 'ANTIOQUIA');
INSERT INTO `registroFinca`.`Departamento` (`idDepartamento`, `nombreDepto`) VALUES ('5', 'CALDAS');

-- -----------------------------------------------------
-- Insert  Tabla Municipio
-- -----------------------------------------------------
INSERT INTO `registroFinca`.`Municipio` (`idMunicipio`, `nombreMpio`, `Departamento_idDepartamento`) VALUES ('1', 'ARMENIA', '1');
INSERT INTO `registroFinca`.`Municipio` (`idMunicipio`, `nombreMpio`, `Departamento_idDepartamento`) VALUES ('2', 'BUENAVISTA', '1');
INSERT INTO `registroFinca`.`Municipio` (`idMunicipio`, `nombreMpio`, `Departamento_idDepartamento`) VALUES ('3', 'CALARCA', '1');
INSERT INTO `registroFinca`.`Municipio` (`idMunicipio`, `nombreMpio`, `Departamento_idDepartamento`) VALUES ('4', 'CIRCASIA', '1');
INSERT INTO `registroFinca`.`Municipio` (`idMunicipio`, `nombreMpio`, `Departamento_idDepartamento`) VALUES ('5', 'CORDOBA', '1');
INSERT INTO `registroFinca`.`Municipio` (`idMunicipio`, `nombreMpio`, `Departamento_idDepartamento`) VALUES ('6', 'FILANDIA', '1');
INSERT INTO `registroFinca`.`Municipio` (`idMunicipio`, `nombreMpio`, `Departamento_idDepartamento`) VALUES ('7', 'GENOVA', '1');
INSERT INTO `registroFinca`.`Municipio` (`idMunicipio`, `nombreMpio`, `Departamento_idDepartamento`) VALUES ('8', 'TEBAIDA', '1');
INSERT INTO `registroFinca`.`Municipio` (`idMunicipio`, `nombreMpio`, `Departamento_idDepartamento`) VALUES ('9', 'MONTENEGRO', '1');
INSERT INTO `registroFinca`.`Municipio` (`idMunicipio`, `nombreMpio`, `Departamento_idDepartamento`) VALUES ('10', 'PIJAO', '1');
INSERT INTO `registroFinca`.`Municipio` (`idMunicipio`, `nombreMpio`, `Departamento_idDepartamento`) VALUES ('11', 'QUIMBAYA', '1');
INSERT INTO `registroFinca`.`Municipio` (`idMunicipio`, `nombreMpio`, `Departamento_idDepartamento`) VALUES ('12', 'SALENTO', '1');
INSERT INTO `registroFinca`.`Municipio` (`idMunicipio`, `nombreMpio`, `Departamento_idDepartamento`) VALUES ('13', 'PEREIRA', '2');
INSERT INTO `registroFinca`.`Municipio` (`idMunicipio`, `nombreMpio`, `Departamento_idDepartamento`) VALUES ('14', 'DOSQUEBRADAS', '2');
INSERT INTO `registroFinca`.`Municipio` (`idMunicipio`, `nombreMpio`, `Departamento_idDepartamento`) VALUES ('15', 'SANTA ROSA', '2');
INSERT INTO `registroFinca`.`Municipio` (`idMunicipio`, `nombreMpio`, `Departamento_idDepartamento`) VALUES ('16', 'MARSELLA', '2');
INSERT INTO `registroFinca`.`Municipio` (`idMunicipio`, `nombreMpio`, `Departamento_idDepartamento`) VALUES ('17', 'BALBOA', '2');
INSERT INTO `registroFinca`.`Municipio` (`idMunicipio`, `nombreMpio`, `Departamento_idDepartamento`) VALUES ('18', 'LA CELIA', '2');
INSERT INTO `registroFinca`.`Municipio` (`idMunicipio`, `nombreMpio`, `Departamento_idDepartamento`) VALUES ('19', 'SANTUARIO', '2');
INSERT INTO `registroFinca`.`Municipio` (`idMunicipio`, `nombreMpio`, `Departamento_idDepartamento`) VALUES ('20', 'APIA', '2');
INSERT INTO `registroFinca`.`Municipio` (`idMunicipio`, `nombreMpio`, `Departamento_idDepartamento`) VALUES ('21', 'CALI', '3');
INSERT INTO `registroFinca`.`Municipio` (`idMunicipio`, `nombreMpio`, `Departamento_idDepartamento`) VALUES ('22', 'CARTAGO', '3');
INSERT INTO `registroFinca`.`Municipio` (`idMunicipio`, `nombreMpio`, `Departamento_idDepartamento`) VALUES ('23', 'ALCALA', '3');
INSERT INTO `registroFinca`.`Municipio` (`idMunicipio`, `nombreMpio`, `Departamento_idDepartamento`) VALUES ('24', 'ULLOA', '3');
INSERT INTO `registroFinca`.`Municipio` (`idMunicipio`, `nombreMpio`, `Departamento_idDepartamento`) VALUES ('25', 'ANSERMA', '3');
INSERT INTO `registroFinca`.`Municipio` (`idMunicipio`, `nombreMpio`, `Departamento_idDepartamento`) VALUES ('26', 'OBANDO', '3');
INSERT INTO `registroFinca`.`Municipio` (`idMunicipio`, `nombreMpio`, `Departamento_idDepartamento`) VALUES ('27', 'ROLDANILLO', '3');
INSERT INTO `registroFinca`.`Municipio` (`idMunicipio`, `nombreMpio`, `Departamento_idDepartamento`) VALUES ('28', 'TULUA', '3');
INSERT INTO `registroFinca`.`Municipio` (`idMunicipio`, `nombreMpio`, `Departamento_idDepartamento`) VALUES ('29', 'BUGA', '3');
INSERT INTO `registroFinca`.`Municipio` (`idMunicipio`, `nombreMpio`, `Departamento_idDepartamento`) VALUES ('30', 'PALMIRA', '3');
INSERT INTO `registroFinca`.`Municipio` (`idMunicipio`, `nombreMpio`, `Departamento_idDepartamento`) VALUES ('31', 'MEDELLIN', '4');
INSERT INTO `registroFinca`.`Municipio` (`idMunicipio`, `nombreMpio`, `Departamento_idDepartamento`) VALUES ('32', 'ENVIGADO', '4');
INSERT INTO `registroFinca`.`Municipio` (`idMunicipio`, `nombreMpio`, `Departamento_idDepartamento`) VALUES ('33', 'SABANETA', '4');
INSERT INTO `registroFinca`.`Municipio` (`idMunicipio`, `nombreMpio`, `Departamento_idDepartamento`) VALUES ('34', 'RIO NEGRO', '4');
INSERT INTO `registroFinca`.`Municipio` (`idMunicipio`, `nombreMpio`, `Departamento_idDepartamento`) VALUES ('35', 'COPACABANA', '4');
INSERT INTO `registroFinca`.`Municipio` (`idMunicipio`, `nombreMpio`, `Departamento_idDepartamento`) VALUES ('36', 'GUATAPE', '4');
INSERT INTO `registroFinca`.`Municipio` (`idMunicipio`, `nombreMpio`, `Departamento_idDepartamento`) VALUES ('37', 'PEÑOL', '4');
INSERT INTO `registroFinca`.`Municipio` (`idMunicipio`, `nombreMpio`, `Departamento_idDepartamento`) VALUES ('38', 'MARINILLA', '4');
INSERT INTO `registroFinca`.`Municipio` (`idMunicipio`, `nombreMpio`, `Departamento_idDepartamento`) VALUES ('39', 'SAN ANTONIO', '4');
INSERT INTO `registroFinca`.`Municipio` (`idMunicipio`, `nombreMpio`, `Departamento_idDepartamento`) VALUES ('40', 'JARDIN', '4');
INSERT INTO `registroFinca`.`Municipio` (`idMunicipio`, `nombreMpio`, `Departamento_idDepartamento`) VALUES ('41', 'MANIZALES', '5');
INSERT INTO `registroFinca`.`Municipio` (`idMunicipio`, `nombreMpio`, `Departamento_idDepartamento`) VALUES ('42', 'RIOSUCIO', '5');
INSERT INTO `registroFinca`.`Municipio` (`idMunicipio`, `nombreMpio`, `Departamento_idDepartamento`) VALUES ('43', 'PENSILVANIA', '5');
INSERT INTO `registroFinca`.`Municipio` (`idMunicipio`, `nombreMpio`, `Departamento_idDepartamento`) VALUES ('44', 'LA DORADA', '5');
INSERT INTO `registroFinca`.`Municipio` (`idMunicipio`, `nombreMpio`, `Departamento_idDepartamento`) VALUES ('45', 'CHINCHINA', '5');
INSERT INTO `registroFinca`.`Municipio` (`idMunicipio`, `nombreMpio`, `Departamento_idDepartamento`) VALUES ('46', 'SALAMINA', '5');
INSERT INTO `registroFinca`.`Municipio` (`idMunicipio`, `nombreMpio`, `Departamento_idDepartamento`) VALUES ('47', 'ANSERMA', '5');
INSERT INTO `registroFinca`.`Municipio` (`idMunicipio`, `nombreMpio`, `Departamento_idDepartamento`) VALUES ('48', 'AGUADAS', '5');
INSERT INTO `registroFinca`.`Municipio` (`idMunicipio`, `nombreMpio`, `Departamento_idDepartamento`) VALUES ('49', 'PALESTINA', '5');
INSERT INTO `registroFinca`.`Municipio` (`idMunicipio`, `nombreMpio`, `Departamento_idDepartamento`) VALUES ('50', 'NEIRA', '5');


SELECT M.nombreMpio AS Municipio, D.nombreDepto AS Departamento
FROM Municipio M JOIN Departamento D ON M.Departamento_idDepartamento  = D.idDepartamento;

SELECT nombreDepto from Municipio M join Departamento D on M.Departamento_idDepartamento = D.idDepartamento where M.idMunicipio = 34;
